package contracts

import (
	"context"
	"database/sql"
	"testing"

	ormapper "github.com/hanpama/ormapper"
)

type Fixture struct {
	Name        string
	DB          *sql.DB
	Dialect     ormapper.Dialect
	ResetSchema func(*testing.T, context.Context, *sql.DB)
	Placeholder func(int) string
}

func Run(t *testing.T, f Fixture) {
	t.Helper()

	t.Run("Persistence", func(t *testing.T) {
		t.Run("SimpleAuto", func(t *testing.T) { runSimpleAuto(t, f) })
		t.Run("SimpleUUID", func(t *testing.T) { runSimpleUUID(t, f) })
		t.Run("Composite", func(t *testing.T) { runComposite(t, f) })
		t.Run("SpecialQuote", func(t *testing.T) { runSpecialQuote(t, f) })
		t.Run("AggregateSave", func(t *testing.T) { runAggregateSave(t, f) })
		t.Run("SingularChildNilDeletes", func(t *testing.T) { runSingularChildNilDeletes(t, f) })
		t.Run("DeleteAggregate", func(t *testing.T) { runDeleteAggregate(t, f) })
	})

	t.Run("Query", func(t *testing.T) {
		t.Run("FetchAndFilter", func(t *testing.T) { runQueryFetchAndFilter(t, f) })
		t.Run("JoinGroupHavingCount", func(t *testing.T) { runQueryJoinGroupHavingCount(t, f) })
	})

	t.Run("Transactions", func(t *testing.T) {
		t.Run("CommitVisible", func(t *testing.T) { runTransactionCommitVisible(t, f) })
		t.Run("RollbackInvisible", func(t *testing.T) { runTransactionRollbackInvisible(t, f) })
	})

	t.Run("Validation", func(t *testing.T) {
		runValidation(t, f)
	})
}

func strPtr(s string) *string {
	return &s
}

func reset(t *testing.T, f Fixture) context.Context {
	t.Helper()

	ctx := context.Background()
	f.ResetSchema(t, ctx, f.DB)
	return ctx
}

func mapperFor(dialect ormapper.Dialect) *ormapper.Mapper {
	return ormapper.MustCompile(
		dialect,
		ormapper.Map(&simpleAuto{}, ormapper.WithTable("simple_auto")),
		ormapper.Map(&simpleUUID{}, ormapper.WithTable("simple_uuid")),
		ormapper.Map(&composite{}, ormapper.WithTable("composite")),
		ormapper.Map(&specialQuote{}, ormapper.WithTable("special quote")),
		ormapper.Map(&order{}, ormapper.WithTable("orders")),
		ormapper.Map(&orderItem{}, ormapper.WithTable("order_items")),
		ormapper.Map(&orderItemLot{}, ormapper.WithTable("order_item_lots")),
		ormapper.Map(&orderNote{}, ormapper.WithTable("order_notes")),
	)
}

func countRows(t *testing.T, ctx context.Context, db *sql.DB, query string, args ...any) int64 {
	t.Helper()

	var count int64
	if err := db.QueryRowContext(ctx, query, args...).Scan(&count); err != nil {
		t.Fatalf("count rows: %v", err)
	}
	return count
}

func assertMissing[T any](t *testing.T, ctx context.Context, m *ormapper.Mapper, db ormapper.DBTX, id ormapper.Key) {
	t.Helper()

	var found *T
	if err := m.Get(ctx, db, &found, id); err != nil {
		t.Fatalf("Get missing: %v", err)
	}
	if found != nil {
		t.Fatalf("expected missing row, got %#v", found)
	}
}

func runSimpleAuto(t *testing.T, f Fixture) {
	ctx := reset(t, f)
	m := mapperFor(f.Dialect)

	entity := &simpleAuto{
		Name:     "created",
		Nullable: strPtr("nullable"),
	}
	if err := m.Save(ctx, f.DB, entity); err != nil {
		t.Fatalf("Save insert: %v", err)
	}
	if entity.ID == 0 {
		t.Fatal("expected auto ID to be backfilled")
	}
	if entity.AutoGenerated != 42 {
		t.Fatalf("expected auto-generated field 42, got %d", entity.AutoGenerated)
	}

	entity.Name = "updated"
	entity.Nullable = strPtr("changed")
	if err := m.Save(ctx, f.DB, entity); err != nil {
		t.Fatalf("Save update: %v", err)
	}

	var loaded *simpleAuto
	if err := m.Get(ctx, f.DB, &loaded, ormapper.NewKey(entity.ID)); err != nil {
		t.Fatalf("Get: %v", err)
	}
	if loaded == nil {
		t.Fatal("expected entity to load")
	}
	if loaded.Name != "updated" {
		t.Fatalf("expected updated name, got %q", loaded.Name)
	}
	if loaded.Nullable == nil || *loaded.Nullable != "changed" {
		t.Fatalf("expected nullable value to round-trip, got %#v", loaded.Nullable)
	}
	if loaded.AutoGenerated != 42 {
		t.Fatalf("expected auto-generated field to remain 42, got %d", loaded.AutoGenerated)
	}
	if countRows(t, ctx, f.DB, "SELECT COUNT(*) FROM simple_auto WHERE id = "+f.Placeholder(1), entity.ID) != 1 {
		t.Fatal("Save of existing entity inserted a duplicate row")
	}
}

func runSimpleUUID(t *testing.T, f Fixture) {
	ctx := reset(t, f)
	m := mapperFor(f.Dialect)

	entity := &simpleUUID{
		ID:       "550e8400-e29b-41d4-a716-446655440000",
		Name:     "uuid",
		Nullable: strPtr("nullable"),
	}
	if err := m.Save(ctx, f.DB, entity); err != nil {
		t.Fatalf("Save explicit key insert: %v", err)
	}
	if entity.AutoGenerated != 42 {
		t.Fatalf("expected auto-generated field 42, got %d", entity.AutoGenerated)
	}

	entity.Name = "uuid-updated"
	entity.Nullable = nil
	if err := m.Save(ctx, f.DB, entity); err != nil {
		t.Fatalf("Save explicit key update: %v", err)
	}

	var loaded *simpleUUID
	if err := m.Get(ctx, f.DB, &loaded, ormapper.NewKey(entity.ID)); err != nil {
		t.Fatalf("Get explicit key: %v", err)
	}
	if loaded == nil || loaded.Name != "uuid-updated" || loaded.Nullable != nil {
		t.Fatalf("unexpected loaded explicit-key entity: %#v", loaded)
	}
}

func runComposite(t *testing.T, f Fixture) {
	ctx := reset(t, f)
	m := mapperFor(f.Dialect)

	entity := &composite{
		Key1:     100,
		Key2:     200,
		Name:     "composite",
		Nullable: strPtr("nullable"),
	}
	if err := m.Save(ctx, f.DB, entity); err != nil {
		t.Fatalf("Save composite insert: %v", err)
	}

	entity.Name = "composite-updated"
	if err := m.Save(ctx, f.DB, entity); err != nil {
		t.Fatalf("Save composite update: %v", err)
	}

	var loaded *composite
	if err := m.Get(ctx, f.DB, &loaded, ormapper.NewKey(entity.Key1, entity.Key2)); err != nil {
		t.Fatalf("Get composite: %v", err)
	}
	if loaded == nil || loaded.Name != "composite-updated" {
		t.Fatalf("unexpected composite entity: %#v", loaded)
	}

	if err := m.Delete(ctx, f.DB, entity); err != nil {
		t.Fatalf("Delete composite: %v", err)
	}
	assertMissing[composite](t, ctx, m, f.DB, ormapper.NewKey(entity.Key1, entity.Key2))
}

func runSpecialQuote(t *testing.T, f Fixture) {
	ctx := reset(t, f)
	m := mapperFor(f.Dialect)

	entity := &specialQuote{Name: "quoted"}
	if err := m.Save(ctx, f.DB, entity); err != nil {
		t.Fatalf("Save special quote: %v", err)
	}

	var loaded *specialQuote
	if err := m.Get(ctx, f.DB, &loaded, ormapper.NewKey(entity.ID)); err != nil {
		t.Fatalf("Get special quote: %v", err)
	}
	if loaded == nil || loaded.Name != "quoted" {
		t.Fatalf("unexpected special quote entity: %#v", loaded)
	}
}

func runAggregateSave(t *testing.T, f Fixture) {
	ctx := reset(t, f)
	m := mapperFor(f.Dialect)

	root := &order{
		CustomerID: 42,
		Total:      100,
		Note:       &orderNote{Body: "initial note"},
		Items: []*orderItem{
			{Name: "apple", Qty: 1, Lots: []*orderItemLot{{Code: "A1"}}},
			{Name: "pear", Qty: 2, Lots: []*orderItemLot{{Code: "P1"}}},
		},
	}

	if err := m.Save(ctx, f.DB, root); err != nil {
		t.Fatalf("Save aggregate insert: %v", err)
	}
	if root.ID == 0 || root.Note.ID == 0 || root.Items[0].ID == 0 || root.Items[0].Lots[0].ID == 0 {
		t.Fatalf("expected generated IDs to be backfilled: %#v", root)
	}
	if root.Items[0].OrderID != root.ID || root.Items[0].Lots[0].OrderItemID != root.Items[0].ID {
		t.Fatalf("expected parental keys to be injected: %#v", root)
	}

	removedItemID := root.Items[0].ID
	removedLotID := root.Items[0].Lots[0].ID
	root.Total = 125
	root.Note.Body = "updated note"
	root.Items[1].Qty = 5
	root.Items[1].Lots = append(root.Items[1].Lots, &orderItemLot{Code: "P2"})
	root.Items = []*orderItem{
		root.Items[1],
		{Name: "orange", Qty: 3, Lots: []*orderItemLot{{Code: "O1"}}},
	}

	if err := m.Save(ctx, f.DB, root); err != nil {
		t.Fatalf("Save aggregate update: %v", err)
	}

	if countRows(t, ctx, f.DB, "SELECT COUNT(*) FROM order_items WHERE id = "+f.Placeholder(1), removedItemID) != 0 {
		t.Fatal("Save should delete child omitted from aggregate snapshot")
	}
	if countRows(t, ctx, f.DB, "SELECT COUNT(*) FROM order_item_lots WHERE id = "+f.Placeholder(1), removedLotID) != 0 {
		t.Fatal("Save should delete grandchildren of omitted child")
	}

	var loaded *order
	if err := m.Get(ctx, f.DB, &loaded, ormapper.NewKey(root.ID)); err != nil {
		t.Fatalf("Get aggregate: %v", err)
	}
	if loaded == nil || loaded.Total != 125 || loaded.Note == nil || loaded.Note.Body != "updated note" {
		t.Fatalf("unexpected aggregate root/note: %#v", loaded)
	}
	if len(loaded.Items) != 2 {
		t.Fatalf("expected 2 items after replacement save, got %#v", loaded.Items)
	}
	for _, item := range loaded.Items {
		if item.OrderID != loaded.ID {
			t.Fatalf("child parental key mismatch: %#v", item)
		}
		for _, lot := range item.Lots {
			if lot.OrderItemID != item.ID {
				t.Fatalf("grandchild parental key mismatch: %#v", lot)
			}
		}
	}
}

func runSingularChildNilDeletes(t *testing.T, f Fixture) {
	ctx := reset(t, f)
	m := mapperFor(f.Dialect)

	root := &order{
		CustomerID: 7,
		Total:      10,
		Note:       &orderNote{Body: "remove me"},
	}
	if err := m.Save(ctx, f.DB, root); err != nil {
		t.Fatalf("Save aggregate with note: %v", err)
	}
	noteID := root.Note.ID

	root.Note = nil
	if err := m.Save(ctx, f.DB, root); err != nil {
		t.Fatalf("Save aggregate without note: %v", err)
	}
	if countRows(t, ctx, f.DB, "SELECT COUNT(*) FROM order_notes WHERE id = "+f.Placeholder(1), noteID) != 0 {
		t.Fatal("Save should delete missing singular child")
	}
}

func runDeleteAggregate(t *testing.T, f Fixture) {
	ctx := reset(t, f)
	m := mapperFor(f.Dialect)

	root := &order{
		CustomerID: 42,
		Total:      50,
		Note:       &orderNote{Body: "delete"},
		Items: []*orderItem{
			{Name: "alpha", Qty: 1, Lots: []*orderItemLot{{Code: "A1"}}},
			{Name: "beta", Qty: 2, Lots: []*orderItemLot{{Code: "B1"}}},
		},
	}
	if err := m.Save(ctx, f.DB, root); err != nil {
		t.Fatalf("Save aggregate: %v", err)
	}

	if err := m.Delete(ctx, f.DB, &order{ID: root.ID}); err != nil {
		t.Fatalf("Delete aggregate: %v", err)
	}

	assertMissing[order](t, ctx, m, f.DB, ormapper.NewKey(root.ID))
	for _, table := range []string{"order_items", "order_item_lots", "order_notes"} {
		if countRows(t, ctx, f.DB, "SELECT COUNT(*) FROM "+table) != 0 {
			t.Fatalf("expected %s rows to be deleted", table)
		}
	}
}

func runQueryFetchAndFilter(t *testing.T, f Fixture) {
	ctx := reset(t, f)
	m := mapperFor(f.Dialect)
	seedOrders(t, ctx, m, f.DB)

	all, err := ormapper.NewQuery[order](m, f.DB, "o").
		OrderBy(ormapper.NewQuery[order](m, f.DB, "o").Asc("o.total")).
		FetchAll(ctx)
	if err != nil {
		t.Fatalf("FetchAll: %v", err)
	}
	if len(all) != 3 {
		t.Fatalf("expected 3 orders, got %d", len(all))
	}

	found, err := ormapper.NewQuery[order](m, f.DB, "o").
		Where("o.customer_id = ?", int64(42)).
		FetchOne(ctx)
	if err != nil {
		t.Fatalf("FetchOne: %v", err)
	}
	if found == nil || len(found.Items) != 2 {
		t.Fatalf("expected aggregate children to load in query result, got %#v", found)
	}

	missing, err := ormapper.NewQuery[order](m, f.DB, "o").
		Where("o.customer_id = ?", int64(999)).
		FetchOne(ctx)
	if err != nil {
		t.Fatalf("FetchOne missing: %v", err)
	}
	if missing != nil {
		t.Fatalf("expected missing query result to be nil, got %#v", missing)
	}

	page, err := ormapper.NewQuery[order](m, f.DB, "o").
		OrderBy(ormapper.NewQuery[order](m, f.DB, "o").Desc("o.total")).
		Offset(1).
		FetchMany(ctx, 1)
	if err != nil {
		t.Fatalf("FetchMany with offset: %v", err)
	}
	if len(page) != 1 || page[0].CustomerID != 42 {
		t.Fatalf("unexpected offset page: %#v", page)
	}
}

func runQueryJoinGroupHavingCount(t *testing.T, f Fixture) {
	ctx := reset(t, f)
	m := mapperFor(f.Dialect)
	seedOrders(t, ctx, m, f.DB)

	count, err := ormapper.NewQuery[order](m, f.DB, "o").
		Join("order_items", "oi", "o.id = oi.order_id").
		GroupByPrimaryKey().
		Having("COUNT(oi.id) >= ?", 2).
		Count(ctx)
	if err != nil {
		t.Fatalf("Count with join/group/having: %v", err)
	}
	if count != 2 {
		t.Fatalf("expected 2 orders with at least 2 items, got %d", count)
	}

	withNoMatch, err := ormapper.NewQuery[order](m, f.DB, "o").
		LeftJoin("order_items", "oi", "o.id = oi.order_id AND oi.name = ?", "does-not-exist").
		Where("oi.id IS NULL").
		FetchAll(ctx)
	if err != nil {
		t.Fatalf("LeftJoin query: %v", err)
	}
	if len(withNoMatch) != 3 {
		t.Fatalf("expected all orders to have no matching item name, got %d", len(withNoMatch))
	}
}

func seedOrders(t *testing.T, ctx context.Context, m *ormapper.Mapper, db *sql.DB) []*order {
	t.Helper()

	orders := []*order{
		{CustomerID: 42, Total: 50, Items: []*orderItem{{Name: "alpha", Qty: 1}, {Name: "beta", Qty: 2}}},
		{CustomerID: 43, Total: 10, Items: []*orderItem{{Name: "gamma", Qty: 3}}},
		{CustomerID: 44, Total: 75, Items: []*orderItem{{Name: "delta", Qty: 4}, {Name: "epsilon", Qty: 5}, {Name: "zeta", Qty: 6}}},
	}
	for _, order := range orders {
		if err := m.Save(ctx, db, order); err != nil {
			t.Fatalf("seed order: %v", err)
		}
	}
	return orders
}

func runTransactionCommitVisible(t *testing.T, f Fixture) {
	ctx := reset(t, f)
	m := mapperFor(f.Dialect)

	tx, err := f.DB.BeginTx(ctx, nil)
	if err != nil {
		t.Fatalf("BeginTx: %v", err)
	}

	entity := &simpleAuto{Name: "committed"}
	if err := m.Save(ctx, tx, entity); err != nil {
		_ = tx.Rollback()
		t.Fatalf("Save in tx: %v", err)
	}
	if err := tx.Commit(); err != nil {
		t.Fatalf("Commit: %v", err)
	}

	var loaded *simpleAuto
	if err := m.Get(ctx, f.DB, &loaded, ormapper.NewKey(entity.ID)); err != nil {
		t.Fatalf("Get after commit: %v", err)
	}
	if loaded == nil || loaded.Name != "committed" {
		t.Fatalf("expected committed row to be visible, got %#v", loaded)
	}
}

func runTransactionRollbackInvisible(t *testing.T, f Fixture) {
	ctx := reset(t, f)
	m := mapperFor(f.Dialect)

	tx, err := f.DB.BeginTx(ctx, nil)
	if err != nil {
		t.Fatalf("BeginTx: %v", err)
	}

	entity := &simpleAuto{Name: "rolled back"}
	if err := m.Save(ctx, tx, entity); err != nil {
		_ = tx.Rollback()
		t.Fatalf("Save in tx: %v", err)
	}
	var insideTx *simpleAuto
	if err := m.Get(ctx, tx, &insideTx, ormapper.NewKey(entity.ID)); err != nil {
		_ = tx.Rollback()
		t.Fatalf("Get inside tx: %v", err)
	}
	if insideTx == nil {
		_ = tx.Rollback()
		t.Fatal("expected row to be visible inside transaction")
	}
	if err := tx.Rollback(); err != nil {
		t.Fatalf("Rollback: %v", err)
	}

	assertMissing[simpleAuto](t, ctx, m, f.DB, ormapper.NewKey(entity.ID))
}

func runValidation(t *testing.T, f Fixture) {
	ctx := reset(t, f)
	m := mapperFor(f.Dialect)

	t.Run("GetDest", func(t *testing.T) {
		var entity *simpleAuto
		if err := m.Get(ctx, f.DB, entity, ormapper.NewKey(int64(1))); err == nil {
			t.Fatal("expected error for non-pointer dest")
		}
		if err := m.Get(ctx, f.DB, &[]*simpleAuto{}, ormapper.NewKey(int64(1))); err == nil {
			t.Fatal("expected error for non entity-pointer dest")
		}
	})

	t.Run("SaveEntity", func(t *testing.T) {
		if err := m.Save(ctx, f.DB, simpleAuto{}); err == nil {
			t.Fatal("expected error for non-pointer entity")
		}
		v := 1
		if err := m.Save(ctx, f.DB, &v); err == nil {
			t.Fatal("expected error for pointer to non-struct")
		}
	})

	t.Run("DeleteEntity", func(t *testing.T) {
		if err := m.Delete(ctx, f.DB, simpleAuto{}); err == nil {
			t.Fatal("expected error for non-pointer entity")
		}
		v := 1
		if err := m.Delete(ctx, f.DB, &v); err == nil {
			t.Fatal("expected error for pointer to non-struct")
		}
	})

	t.Run("UnmappedType", func(t *testing.T) {
		type unmapped struct {
			ID int64
		}
		if err := m.Save(ctx, f.DB, &unmapped{}); err == nil {
			t.Fatal("expected error for unmapped save type")
		}
		var loaded *unmapped
		if err := m.Get(ctx, f.DB, &loaded, ormapper.NewKey(int64(1))); err == nil {
			t.Fatal("expected error for unmapped get type")
		}
	})

	t.Run("KeyLengthMismatch", func(t *testing.T) {
		var loaded *simpleAuto
		if err := m.Get(ctx, f.DB, &loaded, ormapper.NewKey(int64(1), int64(2))); err == nil {
			t.Fatal("expected key length mismatch error")
		}
	})

	t.Run("CompileInvalidMapping", func(t *testing.T) {
		if _, err := ormapper.Compile(f.Dialect, ormapper.Map(nil)); err == nil {
			t.Fatal("expected nil mapping entity error")
		}
		if _, err := ormapper.Compile(f.Dialect, ormapper.Map(simpleAuto{})); err == nil {
			t.Fatal("expected non-pointer mapping entity error")
		}
		if _, err := ormapper.Compile(f.Dialect, ormapper.Map(new(int))); err == nil {
			t.Fatal("expected non-struct mapping entity error")
		}
	})
}
