package contracts

import (
	"context"
	"database/sql"
	"errors"
	"testing"

	ormapper "github.com/hanpama/ormapper"
)

type Fixture struct {
	Name        string
	DB          *sql.DB
	Dialect     ormapper.Dialect
	ResetSchema func(*testing.T, context.Context, *sql.DB)
	Placeholder func(int) string
}

func Run(t *testing.T, f Fixture) {
	t.Helper()

	t.Run("Persistence", func(t *testing.T) {
		t.Run("SimpleAuto", func(t *testing.T) { runSimpleAuto(t, f) })
		t.Run("BulkMapper", func(t *testing.T) { runBulkMapper(t, f) })
		t.Run("GeneratedAutoKeyNotReused", func(t *testing.T) { runGeneratedAutoKeyNotReused(t, f) })
		t.Run("SimpleUUID", func(t *testing.T) { runSimpleUUID(t, f) })
		t.Run("Composite", func(t *testing.T) { runComposite(t, f) })
		t.Run("SpecialQuote", func(t *testing.T) { runSpecialQuote(t, f) })
		t.Run("AggregateSave", func(t *testing.T) { runAggregateSave(t, f) })
		t.Run("GeneratedChildMustExistUnderParent", func(t *testing.T) { runGeneratedChildMustExistUnderParent(t, f) })
		t.Run("DuplicateSubmittedChildKeyFails", func(t *testing.T) { runDuplicateSubmittedChildKeyFails(t, f) })
		t.Run("SingularChildNilDeletes", func(t *testing.T) { runSingularChildNilDeletes(t, f) })
		t.Run("IdentifyingChild", func(t *testing.T) { runIdentifyingChild(t, f) })
		t.Run("DeleteAggregate", func(t *testing.T) { runDeleteAggregate(t, f) })
		t.Run("AggregateSQLFlow", func(t *testing.T) { runAggregateSQLFlow(t, f) })
	})

	t.Run("Query", func(t *testing.T) {
		t.Run("FetchAndFilter", func(t *testing.T) { runQueryFetchAndFilter(t, f) })
		t.Run("JoinGroupHavingCount", func(t *testing.T) { runQueryJoinGroupHavingCount(t, f) })
	})

	t.Run("Transactions", func(t *testing.T) {
		t.Run("CommitVisible", func(t *testing.T) { runTransactionCommitVisible(t, f) })
		t.Run("RollbackInvisible", func(t *testing.T) { runTransactionRollbackInvisible(t, f) })
	})

	t.Run("Validation", func(t *testing.T) {
		runValidation(t, f)
	})
}

func strPtr(s string) *string {
	return &s
}

func reset(t *testing.T, f Fixture) context.Context {
	t.Helper()

	ctx := context.Background()
	f.ResetSchema(t, ctx, f.DB)
	return ctx
}

func mapperFor(dialect ormapper.Dialect) *ormapper.Mapper {
	return ormapper.MustCompile(
		dialect,
		ormapper.Map(&simpleAuto{}, ormapper.WithTable("simple_auto")),
		ormapper.Map(&simpleUUID{}, ormapper.WithTable("simple_uuid")),
		ormapper.Map(&composite{}, ormapper.WithTable("composite")),
		ormapper.Map(&specialQuote{}, ormapper.WithTable("special quote")),
		ormapper.Map(&order{}, ormapper.WithTable("orders")),
		ormapper.Map(&orderItem{}, ormapper.WithTable("order_items")),
		ormapper.Map(&orderItemLot{}, ormapper.WithTable("order_item_lots")),
		ormapper.Map(&orderNote{}, ormapper.WithTable("order_notes")),
		ormapper.Map(&identifyingRoot{}, ormapper.WithTable("identifying_roots")),
		ormapper.Map(&identifyingDetail{}, ormapper.WithTable("identifying_details")),
	)
}

func countRows(t *testing.T, ctx context.Context, db *sql.DB, query string, args ...any) int64 {
	t.Helper()

	var count int64
	if err := db.QueryRowContext(ctx, query, args...).Scan(&count); err != nil {
		t.Fatalf("count rows: %v", err)
	}
	return count
}

func assertMissing[T any](t *testing.T, ctx context.Context, m *ormapper.Mapper, db ormapper.DBTX, id ormapper.Key) {
	t.Helper()

	var found *T
	if err := m.Get(ctx, db, &found, id); err != nil {
		t.Fatalf("Get missing: %v", err)
	}
	if found != nil {
		t.Fatalf("expected missing row, got %#v", found)
	}
}

func runSimpleAuto(t *testing.T, f Fixture) {
	ctx := reset(t, f)
	m := mapperFor(f.Dialect)

	entity := &simpleAuto{
		Name:     "created",
		Nullable: strPtr("nullable"),
	}
	if err := m.Save(ctx, f.DB, entity); err != nil {
		t.Fatalf("Save insert: %v", err)
	}
	if entity.ID == 0 {
		t.Fatal("expected auto ID to be backfilled")
	}
	if entity.AutoGenerated != 42 {
		t.Fatalf("expected auto-generated field 42, got %d", entity.AutoGenerated)
	}

	entity.Name = "updated"
	entity.Nullable = strPtr("changed")
	if err := m.Save(ctx, f.DB, entity); err != nil {
		t.Fatalf("Save update: %v", err)
	}

	var loaded *simpleAuto
	if err := m.Get(ctx, f.DB, &loaded, ormapper.NewKey(entity.ID)); err != nil {
		t.Fatalf("Get: %v", err)
	}
	if loaded == nil {
		t.Fatal("expected entity to load")
	}
	if loaded.Name != "updated" {
		t.Fatalf("expected updated name, got %q", loaded.Name)
	}
	if loaded.Nullable == nil || *loaded.Nullable != "changed" {
		t.Fatalf("expected nullable value to round-trip, got %#v", loaded.Nullable)
	}
	if loaded.AutoGenerated != 42 {
		t.Fatalf("expected auto-generated field to remain 42, got %d", loaded.AutoGenerated)
	}
	if countRows(t, ctx, f.DB, "SELECT COUNT(*) FROM simple_auto WHERE id = "+f.Placeholder(1), entity.ID) != 1 {
		t.Fatal("Save of existing entity inserted a duplicate row")
	}

	stale := &simpleAuto{
		ID:       1000,
		Name:     "stale generated id",
		Nullable: strPtr("should fail"),
	}
	if err := m.Save(ctx, f.DB, stale); !errors.Is(err, ormapper.ErrStaleEntity) {
		t.Fatalf("expected stale generated entity error, got %v", err)
	}
}

func runBulkMapper(t *testing.T, f Fixture) {
	ctx := reset(t, f)
	m := mapperFor(f.Dialect)

	first := &simpleAuto{Name: "bulk-first"}
	second := &simpleAuto{Name: "bulk-second"}
	if err := m.SaveMany(ctx, f.DB, []*simpleAuto{first, second}); err != nil {
		t.Fatalf("SaveMany insert: %v", err)
	}
	if first.ID == 0 || second.ID == 0 || first.ID == second.ID {
		t.Fatalf("expected distinct generated IDs, got first=%d second=%d", first.ID, second.ID)
	}

	var loaded []*simpleAuto
	ids := []ormapper.Key{
		ormapper.NewKey(second.ID),
		ormapper.NewKey(int64(999999)),
		ormapper.NewKey(first.ID),
	}
	if err := m.GetMany(ctx, f.DB, &loaded, ids); err != nil {
		t.Fatalf("GetMany: %v", err)
	}
	if len(loaded) != len(ids) {
		t.Fatalf("expected %d loaded slots, got %d", len(ids), len(loaded))
	}
	if loaded[0] == nil || loaded[0].ID != second.ID || loaded[0].Name != "bulk-second" {
		t.Fatalf("expected second entity in first slot, got %#v", loaded[0])
	}
	if loaded[1] != nil {
		t.Fatalf("expected missing entity slot to be nil, got %#v", loaded[1])
	}
	if loaded[2] == nil || loaded[2].ID != first.ID || loaded[2].Name != "bulk-first" {
		t.Fatalf("expected first entity in third slot, got %#v", loaded[2])
	}

	first.Name = "bulk-first-updated"
	second.Name = "bulk-second-updated"
	if err := m.SaveMany(ctx, f.DB, []*simpleAuto{first, second}); err != nil {
		t.Fatalf("SaveMany update: %v", err)
	}

	loaded = nil
	if err := m.GetMany(ctx, f.DB, &loaded, []ormapper.Key{ormapper.NewKey(first.ID), ormapper.NewKey(second.ID)}); err != nil {
		t.Fatalf("GetMany after update: %v", err)
	}
	if loaded[0] == nil || loaded[0].Name != "bulk-first-updated" {
		t.Fatalf("expected first update, got %#v", loaded[0])
	}
	if loaded[1] == nil || loaded[1].Name != "bulk-second-updated" {
		t.Fatalf("expected second update, got %#v", loaded[1])
	}

	if err := m.DeleteMany(ctx, f.DB, []*simpleAuto{{ID: first.ID}, {ID: second.ID}}); err != nil {
		t.Fatalf("DeleteMany: %v", err)
	}
	if countRows(t, ctx, f.DB, "SELECT COUNT(*) FROM simple_auto WHERE id IN ("+f.Placeholder(1)+", "+f.Placeholder(2)+")", first.ID, second.ID) != 0 {
		t.Fatal("expected DeleteMany to remove both rows")
	}

	var empty []*simpleAuto
	if err := m.GetMany(ctx, f.DB, &empty, nil); err != nil {
		t.Fatalf("GetMany empty: %v", err)
	}
	if len(empty) != 0 {
		t.Fatalf("expected empty GetMany result, got %d", len(empty))
	}
	if err := m.SaveMany(ctx, f.DB, []*simpleAuto{}); err != nil {
		t.Fatalf("SaveMany empty: %v", err)
	}
	if err := m.DeleteMany(ctx, f.DB, []*simpleAuto{}); err != nil {
		t.Fatalf("DeleteMany empty: %v", err)
	}
}

func runGeneratedAutoKeyNotReused(t *testing.T, f Fixture) {
	ctx := reset(t, f)
	m := mapperFor(f.Dialect)

	first := &simpleAuto{Name: "first"}
	if err := m.Save(ctx, f.DB, first); err != nil {
		t.Fatalf("Save first generated entity: %v", err)
	}
	if err := m.Delete(ctx, f.DB, first); err != nil {
		t.Fatalf("Delete first generated entity: %v", err)
	}

	second := &simpleAuto{Name: "second"}
	if err := m.Save(ctx, f.DB, second); err != nil {
		t.Fatalf("Save second generated entity: %v", err)
	}
	if second.ID <= first.ID {
		t.Fatalf("generated key was reused or moved backwards: first=%d second=%d", first.ID, second.ID)
	}
}

func runSimpleUUID(t *testing.T, f Fixture) {
	ctx := reset(t, f)
	m := mapperFor(f.Dialect)

	entity := &simpleUUID{
		ID:       "550e8400-e29b-41d4-a716-446655440000",
		Name:     "uuid",
		Nullable: strPtr("nullable"),
	}
	if err := m.Save(ctx, f.DB, entity); err != nil {
		t.Fatalf("Save explicit key insert: %v", err)
	}
	if entity.AutoGenerated != 42 {
		t.Fatalf("expected auto-generated field 42, got %d", entity.AutoGenerated)
	}

	entity.Name = "uuid-updated"
	entity.Nullable = nil
	if err := m.Save(ctx, f.DB, entity); err != nil {
		t.Fatalf("Save explicit key update: %v", err)
	}

	var loaded *simpleUUID
	if err := m.Get(ctx, f.DB, &loaded, ormapper.NewKey(entity.ID)); err != nil {
		t.Fatalf("Get explicit key: %v", err)
	}
	if loaded == nil || loaded.Name != "uuid-updated" || loaded.Nullable != nil {
		t.Fatalf("unexpected loaded explicit-key entity: %#v", loaded)
	}
	if countRows(t, ctx, f.DB, "SELECT COUNT(*) FROM simple_uuid WHERE id = "+f.Placeholder(1), entity.ID) != 1 {
		t.Fatal("Save of explicit-key entity inserted a duplicate row")
	}
}

func runComposite(t *testing.T, f Fixture) {
	ctx := reset(t, f)
	m := mapperFor(f.Dialect)

	entity := &composite{
		Key1:     100,
		Key2:     200,
		Name:     "composite",
		Nullable: strPtr("nullable"),
	}
	if err := m.Save(ctx, f.DB, entity); err != nil {
		t.Fatalf("Save composite insert: %v", err)
	}

	entity.Name = "composite-updated"
	if err := m.Save(ctx, f.DB, entity); err != nil {
		t.Fatalf("Save composite update: %v", err)
	}

	var loaded *composite
	if err := m.Get(ctx, f.DB, &loaded, ormapper.NewKey(entity.Key1, entity.Key2)); err != nil {
		t.Fatalf("Get composite: %v", err)
	}
	if loaded == nil || loaded.Name != "composite-updated" {
		t.Fatalf("unexpected composite entity: %#v", loaded)
	}
	if countRows(t, ctx, f.DB, "SELECT COUNT(*) FROM composite WHERE key1 = "+f.Placeholder(1)+" AND key2 = "+f.Placeholder(2), entity.Key1, entity.Key2) != 1 {
		t.Fatal("Save of composite entity inserted a duplicate row")
	}

	if err := m.Delete(ctx, f.DB, entity); err != nil {
		t.Fatalf("Delete composite: %v", err)
	}
	assertMissing[composite](t, ctx, m, f.DB, ormapper.NewKey(entity.Key1, entity.Key2))
}

func runSpecialQuote(t *testing.T, f Fixture) {
	ctx := reset(t, f)
	m := mapperFor(f.Dialect)

	entity := &specialQuote{Name: "quoted"}
	if err := m.Save(ctx, f.DB, entity); err != nil {
		t.Fatalf("Save special quote: %v", err)
	}

	var loaded *specialQuote
	if err := m.Get(ctx, f.DB, &loaded, ormapper.NewKey(entity.ID)); err != nil {
		t.Fatalf("Get special quote: %v", err)
	}
	if loaded == nil || loaded.Name != "quoted" {
		t.Fatalf("unexpected special quote entity: %#v", loaded)
	}
}

func runAggregateSave(t *testing.T, f Fixture) {
	ctx := reset(t, f)
	m := mapperFor(f.Dialect)

	root := &order{
		CustomerID: 42,
		Total:      100,
		Note:       &orderNote{Body: "initial note"},
		Items: []*orderItem{
			{Name: "apple", Qty: 1, Lots: []*orderItemLot{{Code: "A1"}}},
			{Name: "pear", Qty: 2, Lots: []*orderItemLot{{Code: "P1"}}},
		},
	}

	if err := m.Save(ctx, f.DB, root); err != nil {
		t.Fatalf("Save aggregate insert: %v", err)
	}
	if root.ID == 0 || root.Note.ID == 0 || root.Items[0].ID == 0 || root.Items[0].Lots[0].ID == 0 {
		t.Fatalf("expected generated IDs to be backfilled: %#v", root)
	}
	if root.Items[0].OrderID != root.ID || root.Items[0].Lots[0].OrderItemID != root.Items[0].ID {
		t.Fatalf("expected parental keys to be injected: %#v", root)
	}

	removedItemID := root.Items[0].ID
	removedLotID := root.Items[0].Lots[0].ID
	root.Total = 125
	root.Note.Body = "updated note"
	root.Items[1].Qty = 5
	root.Items[1].Lots = append(root.Items[1].Lots, &orderItemLot{Code: "P2"})
	root.Items = []*orderItem{
		root.Items[1],
		{Name: "orange", Qty: 3, Lots: []*orderItemLot{{Code: "O1"}}},
	}

	if err := m.Save(ctx, f.DB, root); err != nil {
		t.Fatalf("Save aggregate update: %v", err)
	}

	if countRows(t, ctx, f.DB, "SELECT COUNT(*) FROM order_items WHERE id = "+f.Placeholder(1), removedItemID) != 0 {
		t.Fatal("Save should delete child omitted from aggregate snapshot")
	}
	if countRows(t, ctx, f.DB, "SELECT COUNT(*) FROM order_item_lots WHERE id = "+f.Placeholder(1), removedLotID) != 0 {
		t.Fatal("Save should delete grandchildren of omitted child")
	}

	var loaded *order
	if err := m.Get(ctx, f.DB, &loaded, ormapper.NewKey(root.ID)); err != nil {
		t.Fatalf("Get aggregate: %v", err)
	}
	if loaded == nil || loaded.Total != 125 || loaded.Note == nil || loaded.Note.Body != "updated note" {
		t.Fatalf("unexpected aggregate root/note: %#v", loaded)
	}
	if len(loaded.Items) != 2 {
		t.Fatalf("expected 2 items after replacement save, got %#v", loaded.Items)
	}
	for _, item := range loaded.Items {
		if item.OrderID != loaded.ID {
			t.Fatalf("child parental key mismatch: %#v", item)
		}
		for _, lot := range item.Lots {
			if lot.OrderItemID != item.ID {
				t.Fatalf("grandchild parental key mismatch: %#v", lot)
			}
		}
	}
}

func runSingularChildNilDeletes(t *testing.T, f Fixture) {
	ctx := reset(t, f)
	m := mapperFor(f.Dialect)

	root := &order{
		CustomerID: 7,
		Total:      10,
		Note:       &orderNote{Body: "remove me"},
	}
	if err := m.Save(ctx, f.DB, root); err != nil {
		t.Fatalf("Save aggregate with note: %v", err)
	}
	noteID := root.Note.ID

	root.Note = nil
	if err := m.Save(ctx, f.DB, root); err != nil {
		t.Fatalf("Save aggregate without note: %v", err)
	}
	if countRows(t, ctx, f.DB, "SELECT COUNT(*) FROM order_notes WHERE id = "+f.Placeholder(1), noteID) != 0 {
		t.Fatal("Save should delete missing singular child")
	}
}

func runGeneratedChildMustExistUnderParent(t *testing.T, f Fixture) {
	ctx := reset(t, f)
	m := mapperFor(f.Dialect)

	source := &order{
		CustomerID: 10,
		Total:      10,
		Items:      []*orderItem{{Name: "source", Qty: 1}},
	}
	target := &order{
		CustomerID: 20,
		Total:      20,
	}
	if err := m.Save(ctx, f.DB, source); err != nil {
		t.Fatalf("Save source aggregate: %v", err)
	}
	if err := m.Save(ctx, f.DB, target); err != nil {
		t.Fatalf("Save target aggregate: %v", err)
	}

	moved := source.Items[0]
	target.Items = []*orderItem{moved}
	if err := m.Save(ctx, f.DB, target); !errors.Is(err, ormapper.ErrStaleEntity) {
		t.Fatalf("expected stale generated child error, got %v", err)
	}

	rows := countRows(t, ctx, f.DB, "SELECT COUNT(*) FROM order_items WHERE id = "+f.Placeholder(1)+" AND order_id = "+f.Placeholder(2), moved.ID, source.ID)
	if rows != 1 {
		t.Fatal("failed child reparent attempt should not move the stored row")
	}
}

func runDuplicateSubmittedChildKeyFails(t *testing.T, f Fixture) {
	ctx := reset(t, f)
	m := mapperFor(f.Dialect)

	root := &order{
		CustomerID: 30,
		Total:      30,
		Items:      []*orderItem{{Name: "dup", Qty: 1}},
	}
	if err := m.Save(ctx, f.DB, root); err != nil {
		t.Fatalf("Save aggregate: %v", err)
	}

	item := root.Items[0]
	root.Items = []*orderItem{item, item}
	if err := m.Save(ctx, f.DB, root); !errors.Is(err, ormapper.ErrConsistency) {
		t.Fatalf("expected duplicate submitted child key consistency error, got %v", err)
	}
}

func runIdentifyingChild(t *testing.T, f Fixture) {
	ctx := reset(t, f)
	m := mapperFor(f.Dialect)

	root := &identifyingRoot{
		Name:   "root",
		Detail: &identifyingDetail{Body: "detail"},
	}
	if err := m.Save(ctx, f.DB, root); err != nil {
		t.Fatalf("Save identifying root: %v", err)
	}
	if root.ID == 0 || root.Detail.RootID != root.ID {
		t.Fatalf("expected identifying child key injection, got %#v", root)
	}

	root.Detail = nil
	if err := m.Save(ctx, f.DB, root); err != nil {
		t.Fatalf("Save identifying root without detail: %v", err)
	}
	if countRows(t, ctx, f.DB, "SELECT COUNT(*) FROM identifying_details WHERE root_id = "+f.Placeholder(1), root.ID) != 0 {
		t.Fatal("Save should delete missing identifying child")
	}
}

func runDeleteAggregate(t *testing.T, f Fixture) {
	ctx := reset(t, f)
	m := mapperFor(f.Dialect)

	root := &order{
		CustomerID: 42,
		Total:      50,
		Note:       &orderNote{Body: "delete"},
		Items: []*orderItem{
			{Name: "alpha", Qty: 1, Lots: []*orderItemLot{{Code: "A1"}}},
			{Name: "beta", Qty: 2, Lots: []*orderItemLot{{Code: "B1"}}},
		},
	}
	if err := m.Save(ctx, f.DB, root); err != nil {
		t.Fatalf("Save aggregate: %v", err)
	}

	if err := m.Delete(ctx, f.DB, &order{ID: root.ID}); err != nil {
		t.Fatalf("Delete aggregate: %v", err)
	}

	assertMissing[order](t, ctx, m, f.DB, ormapper.NewKey(root.ID))
	for _, table := range []string{"order_items", "order_item_lots", "order_notes"} {
		if countRows(t, ctx, f.DB, "SELECT COUNT(*) FROM "+table) != 0 {
			t.Fatalf("expected %s rows to be deleted", table)
		}
	}
}

func runAggregateSQLFlow(t *testing.T, f Fixture) {
	t.Run("NewGeneratedAggregate", func(t *testing.T) {
		ctx := reset(t, f)
		m := mapperFor(f.Dialect)
		trace := newTraceDB(f.DB)
		root := &order{
			CustomerID: 42,
			Total:      100,
			Note:       &orderNote{Body: "initial note"},
			Items: []*orderItem{
				{Name: "apple", Qty: 1, Lots: []*orderItemLot{{Code: "A1"}}},
				{Name: "pear", Qty: 2, Lots: []*orderItemLot{{Code: "P1"}}},
			},
		}

		got, err := trace.capture(func() error {
			return m.Save(ctx, trace, root)
		})
		if err != nil {
			t.Fatalf("Save: %v", err)
		}
		assertSQLFlow(t, got, []string{
			"INSERT orders",
			"INSERT order_notes",
			"INSERT order_items",
			"INSERT order_item_lots",
		})
	})

	t.Run("ExistingMixedAggregate", func(t *testing.T) {
		ctx := reset(t, f)
		m := mapperFor(f.Dialect)
		root := &order{
			CustomerID: 42,
			Total:      100,
			Note:       &orderNote{Body: "initial note"},
			Items: []*orderItem{
				{Name: "apple", Qty: 1, Lots: []*orderItemLot{{Code: "A1"}}},
				{Name: "pear", Qty: 2, Lots: []*orderItemLot{{Code: "P1"}}},
			},
		}
		if err := m.Save(ctx, f.DB, root); err != nil {
			t.Fatalf("seed aggregate: %v", err)
		}

		root.Total = 125
		root.Note.Body = "updated note"
		root.Items[1].Qty = 5
		root.Items[1].Lots = append(root.Items[1].Lots, &orderItemLot{Code: "P2"})
		root.Items = []*orderItem{
			root.Items[1],
			{Name: "orange", Qty: 3, Lots: []*orderItemLot{{Code: "O1"}}},
		}

		trace := newTraceDB(f.DB)
		got, err := trace.capture(func() error {
			return m.Save(ctx, trace, root)
		})
		if err != nil {
			t.Fatalf("Save: %v", err)
		}
		assertSQLFlow(t, got, []string{
			"EXISTS orders",
			"UPDATE orders",
			"LOAD order_notes",
			"UPDATE order_notes",
			"LOAD order_items",
			"INSERT order_items",
			"UPDATE order_items",
			"LOAD order_item_lots",
			"INSERT order_item_lots",
			"UPDATE order_item_lots",
			"LOAD order_item_lots",
			"DELETE order_item_lots",
			"DELETE order_items",
		})
	})

	t.Run("SingularChildNilDeletes", func(t *testing.T) {
		ctx := reset(t, f)
		m := mapperFor(f.Dialect)
		root := &order{
			CustomerID: 7,
			Total:      10,
			Note:       &orderNote{Body: "remove me"},
		}
		if err := m.Save(ctx, f.DB, root); err != nil {
			t.Fatalf("seed aggregate: %v", err)
		}

		root.Note = nil
		trace := newTraceDB(f.DB)
		got, err := trace.capture(func() error {
			return m.Save(ctx, trace, root)
		})
		if err != nil {
			t.Fatalf("Save: %v", err)
		}
		assertSQLFlow(t, got, []string{
			"EXISTS orders",
			"UPDATE orders",
			"LOAD order_notes",
			"DELETE order_notes",
			"LOAD order_items",
		})
	})

	t.Run("ExplicitGeneratedRootMissingFails", func(t *testing.T) {
		ctx := reset(t, f)
		m := mapperFor(f.Dialect)
		root := &order{
			ID:         1000,
			CustomerID: 42,
			Total:      100,
			Note:       &orderNote{Body: "explicit root"},
		}

		trace := newTraceDB(f.DB)
		got, err := trace.capture(func() error {
			return m.Save(ctx, trace, root)
		})
		if !errors.Is(err, ormapper.ErrStaleEntity) {
			t.Fatalf("expected stale generated root error, got %v", err)
		}
		assertSQLFlow(t, got, []string{
			"EXISTS orders",
		})
	})

	t.Run("CompositeKeyInsert", func(t *testing.T) {
		ctx := reset(t, f)
		m := mapperFor(f.Dialect)
		entity := &composite{
			Key1: 100,
			Key2: 200,
			Name: "composite",
		}

		trace := newTraceDB(f.DB)
		got, err := trace.capture(func() error {
			return m.Save(ctx, trace, entity)
		})
		if err != nil {
			t.Fatalf("Save: %v", err)
		}
		assertSQLFlow(t, got, []string{
			"EXISTS composite",
			"INSERT composite",
		})
	})

	t.Run("DeleteAggregate", func(t *testing.T) {
		ctx := reset(t, f)
		m := mapperFor(f.Dialect)
		root := &order{
			CustomerID: 42,
			Total:      50,
			Note:       &orderNote{Body: "delete"},
			Items: []*orderItem{
				{Name: "alpha", Qty: 1, Lots: []*orderItemLot{{Code: "A1"}}},
				{Name: "beta", Qty: 2, Lots: []*orderItemLot{{Code: "B1"}}},
			},
		}
		if err := m.Save(ctx, f.DB, root); err != nil {
			t.Fatalf("seed aggregate: %v", err)
		}

		trace := newTraceDB(f.DB)
		got, err := trace.capture(func() error {
			return m.Delete(ctx, trace, &order{ID: root.ID})
		})
		if err != nil {
			t.Fatalf("Delete: %v", err)
		}
		assertSQLFlow(t, got, []string{
			"LOAD order_notes",
			"DELETE order_notes",
			"LOAD order_items",
			"LOAD order_item_lots",
			"DELETE order_item_lots",
			"DELETE order_items",
			"DELETE orders",
		})
	})
}

func runQueryFetchAndFilter(t *testing.T, f Fixture) {
	ctx := reset(t, f)
	m := mapperFor(f.Dialect)
	seedOrders(t, ctx, m, f.DB)

	all, err := ormapper.NewQuery[order](m, f.DB, "o").
		OrderBy(ormapper.NewQuery[order](m, f.DB, "o").Asc("o.total")).
		FetchAll(ctx)
	if err != nil {
		t.Fatalf("FetchAll: %v", err)
	}
	if len(all) != 3 {
		t.Fatalf("expected 3 orders, got %d", len(all))
	}

	found, err := ormapper.NewQuery[order](m, f.DB, "o").
		Where("o.customer_id = ?", int64(42)).
		FetchOne(ctx)
	if err != nil {
		t.Fatalf("FetchOne: %v", err)
	}
	if found == nil || len(found.Items) != 2 {
		t.Fatalf("expected aggregate children to load in query result, got %#v", found)
	}

	missing, err := ormapper.NewQuery[order](m, f.DB, "o").
		Where("o.customer_id = ?", int64(999)).
		FetchOne(ctx)
	if err != nil {
		t.Fatalf("FetchOne missing: %v", err)
	}
	if missing != nil {
		t.Fatalf("expected missing query result to be nil, got %#v", missing)
	}

	page, err := ormapper.NewQuery[order](m, f.DB, "o").
		OrderBy(ormapper.NewQuery[order](m, f.DB, "o").Desc("o.total")).
		Offset(1).
		FetchMany(ctx, 1)
	if err != nil {
		t.Fatalf("FetchMany with offset: %v", err)
	}
	if len(page) != 1 || page[0].CustomerID != 42 {
		t.Fatalf("unexpected offset page: %#v", page)
	}
}

func runQueryJoinGroupHavingCount(t *testing.T, f Fixture) {
	ctx := reset(t, f)
	m := mapperFor(f.Dialect)
	seedOrders(t, ctx, m, f.DB)

	count, err := ormapper.NewQuery[order](m, f.DB, "o").
		Join("order_items", "oi", "o.id = oi.order_id").
		GroupByPrimaryKey().
		Having("COUNT(oi.id) >= ?", 2).
		Count(ctx)
	if err != nil {
		t.Fatalf("Count with join/group/having: %v", err)
	}
	if count != 2 {
		t.Fatalf("expected 2 orders with at least 2 items, got %d", count)
	}

	withNoMatch, err := ormapper.NewQuery[order](m, f.DB, "o").
		LeftJoin("order_items", "oi", "o.id = oi.order_id AND oi.name = ?", "does-not-exist").
		Where("oi.id IS NULL").
		FetchAll(ctx)
	if err != nil {
		t.Fatalf("LeftJoin query: %v", err)
	}
	if len(withNoMatch) != 3 {
		t.Fatalf("expected all orders to have no matching item name, got %d", len(withNoMatch))
	}
}

func seedOrders(t *testing.T, ctx context.Context, m *ormapper.Mapper, db *sql.DB) []*order {
	t.Helper()

	orders := []*order{
		{CustomerID: 42, Total: 50, Items: []*orderItem{{Name: "alpha", Qty: 1}, {Name: "beta", Qty: 2}}},
		{CustomerID: 43, Total: 10, Items: []*orderItem{{Name: "gamma", Qty: 3}}},
		{CustomerID: 44, Total: 75, Items: []*orderItem{{Name: "delta", Qty: 4}, {Name: "epsilon", Qty: 5}, {Name: "zeta", Qty: 6}}},
	}
	for _, order := range orders {
		if err := m.Save(ctx, db, order); err != nil {
			t.Fatalf("seed order: %v", err)
		}
	}
	return orders
}

func runTransactionCommitVisible(t *testing.T, f Fixture) {
	ctx := reset(t, f)
	m := mapperFor(f.Dialect)

	tx, err := f.DB.BeginTx(ctx, nil)
	if err != nil {
		t.Fatalf("BeginTx: %v", err)
	}

	entity := &simpleAuto{Name: "committed"}
	if err := m.Save(ctx, tx, entity); err != nil {
		_ = tx.Rollback()
		t.Fatalf("Save in tx: %v", err)
	}
	if err := tx.Commit(); err != nil {
		t.Fatalf("Commit: %v", err)
	}

	var loaded *simpleAuto
	if err := m.Get(ctx, f.DB, &loaded, ormapper.NewKey(entity.ID)); err != nil {
		t.Fatalf("Get after commit: %v", err)
	}
	if loaded == nil || loaded.Name != "committed" {
		t.Fatalf("expected committed row to be visible, got %#v", loaded)
	}
}

func runTransactionRollbackInvisible(t *testing.T, f Fixture) {
	ctx := reset(t, f)
	m := mapperFor(f.Dialect)

	tx, err := f.DB.BeginTx(ctx, nil)
	if err != nil {
		t.Fatalf("BeginTx: %v", err)
	}

	entity := &simpleAuto{Name: "rolled back"}
	if err := m.Save(ctx, tx, entity); err != nil {
		_ = tx.Rollback()
		t.Fatalf("Save in tx: %v", err)
	}
	var insideTx *simpleAuto
	if err := m.Get(ctx, tx, &insideTx, ormapper.NewKey(entity.ID)); err != nil {
		_ = tx.Rollback()
		t.Fatalf("Get inside tx: %v", err)
	}
	if insideTx == nil {
		_ = tx.Rollback()
		t.Fatal("expected row to be visible inside transaction")
	}
	if err := tx.Rollback(); err != nil {
		t.Fatalf("Rollback: %v", err)
	}

	assertMissing[simpleAuto](t, ctx, m, f.DB, ormapper.NewKey(entity.ID))
}

func runValidation(t *testing.T, f Fixture) {
	ctx := reset(t, f)
	m := mapperFor(f.Dialect)

	t.Run("GetDest", func(t *testing.T) {
		var entity *simpleAuto
		if err := m.Get(ctx, f.DB, entity, ormapper.NewKey(int64(1))); err == nil {
			t.Fatal("expected error for non-pointer dest")
		}
		if err := m.Get(ctx, f.DB, &[]*simpleAuto{}, ormapper.NewKey(int64(1))); err == nil {
			t.Fatal("expected error for non entity-pointer dest")
		}
	})

	t.Run("GetManyDest", func(t *testing.T) {
		var entities []*simpleAuto
		if err := m.GetMany(ctx, f.DB, entities, []ormapper.Key{ormapper.NewKey(int64(1))}); err == nil {
			t.Fatal("expected error for non-pointer dest")
		}
		if err := m.GetMany(ctx, f.DB, &[]simpleAuto{}, []ormapper.Key{ormapper.NewKey(int64(1))}); err == nil {
			t.Fatal("expected error for non entity-pointer slice dest")
		}
	})

	t.Run("SaveEntity", func(t *testing.T) {
		if err := m.Save(ctx, f.DB, simpleAuto{}); err == nil {
			t.Fatal("expected error for non-pointer entity")
		}
		v := 1
		if err := m.Save(ctx, f.DB, &v); err == nil {
			t.Fatal("expected error for pointer to non-struct")
		}
	})

	t.Run("SaveManyEntities", func(t *testing.T) {
		if err := m.SaveMany(ctx, f.DB, simpleAuto{}); err == nil {
			t.Fatal("expected error for non-slice entities")
		}
		if err := m.SaveMany(ctx, f.DB, []simpleAuto{}); err == nil {
			t.Fatal("expected error for non-pointer entity slice")
		}
		if err := m.SaveMany(ctx, f.DB, []*simpleAuto{nil}); err == nil {
			t.Fatal("expected error for nil entity")
		}
	})

	t.Run("DeleteEntity", func(t *testing.T) {
		if err := m.Delete(ctx, f.DB, simpleAuto{}); err == nil {
			t.Fatal("expected error for non-pointer entity")
		}
		v := 1
		if err := m.Delete(ctx, f.DB, &v); err == nil {
			t.Fatal("expected error for pointer to non-struct")
		}
	})

	t.Run("DeleteManyEntities", func(t *testing.T) {
		if err := m.DeleteMany(ctx, f.DB, simpleAuto{}); err == nil {
			t.Fatal("expected error for non-slice entities")
		}
		if err := m.DeleteMany(ctx, f.DB, []simpleAuto{}); err == nil {
			t.Fatal("expected error for non-pointer entity slice")
		}
		if err := m.DeleteMany(ctx, f.DB, []*simpleAuto{nil}); err == nil {
			t.Fatal("expected error for nil entity")
		}
	})

	t.Run("UnmappedType", func(t *testing.T) {
		type unmapped struct {
			ID int64
		}
		if err := m.Save(ctx, f.DB, &unmapped{}); err == nil {
			t.Fatal("expected error for unmapped save type")
		}
		var loaded *unmapped
		if err := m.Get(ctx, f.DB, &loaded, ormapper.NewKey(int64(1))); err == nil {
			t.Fatal("expected error for unmapped get type")
		}
	})

	t.Run("KeyLengthMismatch", func(t *testing.T) {
		var loaded *simpleAuto
		if err := m.Get(ctx, f.DB, &loaded, ormapper.NewKey(int64(1), int64(2))); err == nil {
			t.Fatal("expected key length mismatch error")
		}
	})

	t.Run("CompileInvalidMapping", func(t *testing.T) {
		if _, err := ormapper.Compile(f.Dialect, ormapper.Map(nil)); err == nil {
			t.Fatal("expected nil mapping entity error")
		}
		if _, err := ormapper.Compile(f.Dialect, ormapper.Map(simpleAuto{})); err == nil {
			t.Fatal("expected non-pointer mapping entity error")
		}
		if _, err := ormapper.Compile(f.Dialect, ormapper.Map(new(int))); err == nil {
			t.Fatal("expected non-struct mapping entity error")
		}
	})
}
