package contracts

type simpleAuto struct {
	ID            int64 `ormapper:"auto"`
	Name          string
	Nullable      *string
	AutoGenerated int `ormapper:"auto"`
}

type simpleUUID struct {
	ID            string `ormapper:"primary"`
	Name          string
	Nullable      *string
	AutoGenerated int `ormapper:"auto"`
}

type composite struct {
	Key1     int `ormapper:"primary"`
	Key2     int `ormapper:"primary"`
	Name     string
	Nullable *string
}

type specialQuote struct {
	ID   int64  `ormapper:"auto"`
	Name string `ormapper:"column:select"`
}

type order struct {
	ID         int64 `ormapper:"auto"`
	CustomerID int64
	Total      float64
	Note       *orderNote
	Items      []*orderItem
}

type orderItem struct {
	ID      int64 `ormapper:"auto"`
	OrderID int64 `ormapper:"parental"`
	Name    string
	Qty     int
	Lots    []*orderItemLot
}

type orderItemLot struct {
	ID          int64 `ormapper:"auto"`
	OrderItemID int64 `ormapper:"parental"`
	Code        string
}

type orderNote struct {
	ID      int64 `ormapper:"auto"`
	OrderID int64 `ormapper:"parental"`
	Body    string
}

type identifyingRoot struct {
	ID     int64 `ormapper:"auto"`
	Name   string
	Detail *identifyingDetail
}

type identifyingDetail struct {
	RootID int64 `ormapper:"primary,parental"`
	Body   string
}
